theme: jekyll-theme-cayman
title: Détagnon's github page
description: My Name is Détagnon Bernic GBAGUIDI.Passionate about science and technology, this page is for sharing an overview of my different works.
