theme: jekyll-theme-hacker
title: Détagnon's github page
description: My Name is Détagnon Bernic GBAGUIDI.Passionate about science and technology, this page is for sharing an overview of my different works. You can download my CV [here](https://drive.google.com/uc?export=download&id=1Xndrc1c09wFRtfyx5b3BSpxr7IldHnnl)
