title: Détagnon's github page
description: I am Détagnon Bernic GBAGUIDI, passionate about science and technology. This page showcases an overview of my projects and research.
theme: jekyll-theme-cayman
